"""Emit AOSP LatinIME English artifacts for uMate.

English is not Chinese lemma-store content. Lexicon still owns the emit so
uMate does not keep a long-lived third-party English table outside this
factory. Apache-2.0 LatinIME wordlist → `aosp_en.dict.yaml` (full Rime
table) plus `en_us_unigrams.tsv` (Swift EnglishLexicon truncation).
"""

from __future__ import annotations

import re
from pathlib import Path

ROW = re.compile(r"\s*word=([a-zA-Z]+),f=(\d+)")


def load_aosp_wordlist(csv_path: Path) -> list[tuple[str, int]]:
    best: dict[str, int] = {}
    with csv_path.open(encoding="utf-8", errors="replace") as handle:
        for line in handle:
            match = ROW.match(line.strip())
            if not match:
                continue
            word = match.group(1).lower()
            weight = int(match.group(2))
            best[word] = max(best.get(word, 0), weight)
    return sorted(best.items(), key=lambda item: (-item[1], item[0]))


def emit_aosp_en(
    csv_path: Path,
    out_dir: Path,
    *,
    min_length: int = 4,
    unigram_limit: int = 20_000,
    snapshot_note: str = "snapshot from Lexicon emit",
) -> dict[str, int]:
    words = [
        (word, weight)
        for word, weight in load_aosp_wordlist(csv_path)
        if len(word) >= min_length and word.isascii() and word.isalpha()
    ]
    out_dir.mkdir(parents=True, exist_ok=True)
    dict_path = out_dir / "aosp_en.dict.yaml"
    _write_dict(dict_path, words, snapshot_note)
    tsv_path = out_dir / "en_us_unigrams.tsv"
    _write_unigrams(tsv_path, words[:unigram_limit])
    schema_path = out_dir / "aosp_en.schema.yaml"
    _write_schema(schema_path)
    return {
        "aosp_en_words": len(words),
        "en_us_unigrams": min(unigram_limit, len(words)),
    }


def _write_dict(path: Path, words: list[tuple[str, int]], snapshot_note: str) -> None:
    lines = [
        "# Rime dictionary",
        "# encoding: utf-8",
        "#",
        "# AOSP LatinIME English unigrams for table_translator@aosp_en.",
        f"# Source: AOSP LatinIME en_US_wordlist.combined (Apache-2.0). {snapshot_note}",
        f"# Full alphabetic coverage: {len(words)} words (≥4 letters),",
        "# weight = upstream LatinIME frequency f (0-255, higher = more frequent).",
        "# Generated by umate-lexicon. Do not hand-edit.",
        "---",
        "name: aosp_en",
        'version: "2"',
        "sort: by_weight",
        "...",
        "",
    ]
    for word, weight in words:
        lines.append(f"{word}\t{word}\t{weight}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_unigrams(path: Path, words: list[tuple[str, int]]) -> None:
    lines = [
        "# uMate English unigram list (~20k)",
        "# Source: AOSP LatinIME dictionaries/en_US_wordlist.combined (Apache-2.0)",
        "# Generated by umate-lexicon. Do not hand-edit.",
    ]
    for word, weight in words:
        lines.append(f"{word}\t{weight}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_schema(path: Path) -> None:
    path.write_text(
        """# Rime schema
# encoding: utf-8
# Generated by umate-lexicon. Wire from uMate; do not copy community eng packs.

schema:
  schema_id: aosp_en
  name: "AOSP English"
  version: "2"

switches:
  - name: ascii_mode
    reset: 1
    states: [ 中文, 西文 ]

engine:
  processors:
    - ascii_composer
    - key_binder
    - speller
    - recognizer
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - table_translator
  filters:
    - uniquifier

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  delimiter: " '"

translator:
  dictionary: aosp_en
  enable_completion: false
  enable_sentence: false
  enable_user_dict: false
  initial_quality: -1

punctuator:
  import_preset: default

key_binder:
  import_preset: default

recognizer:
  import_preset: default
""",
        encoding="utf-8",
    )
