from __future__ import annotations

from collections import defaultdict
from pathlib import Path
import shutil

from umate_lexicon.emit.aosp_en import emit_aosp_en
from umate_lexicon.ingest.emoji import emoji_opencc_sidecar
from umate_lexicon.layers import PACK_LAYERS, assign_layer, emit_weight
from umate_lexicon.lemma import Lemma
from umate_lexicon.pinyin import sanitize_emit_code
from umate_lexicon.store import LemmaStore

LATIN_SYLLABLES = [(ch, ch) for ch in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"]
DIGIT_SYLLABLES = [
    ("0", "ling"),
    ("1", "yi"),
    ("1", "yao"),
    ("2", "er"),
    ("3", "san"),
    ("4", "si"),
    ("5", "wu"),
    ("6", "liu"),
    ("7", "qi"),
    ("8", "ba"),
    ("9", "jiu"),
]


def emit_rime(store: LemmaStore, out_dir: Path, version: str = "0.1.0") -> dict[str, int]:
    out_dir.mkdir(parents=True, exist_ok=True)
    buckets: dict[str, list[Lemma]] = defaultdict(list)
    for lemma in store.all_lemmas():
        layer = assign_layer(lemma)
        if layer is None:
            continue
        buckets[layer].append(lemma)

    sanitized = 0
    dropped = 0
    for name, items in list(buckets.items()):
        cleaned: list[Lemma] = []
        for lemma in items:
            code = sanitize_emit_code(lemma.pinyin_plain)
            if code is None:
                dropped += 1
                continue
            if code != lemma.pinyin_plain:
                sanitized += 1
                lemma = Lemma(
                    surface=lemma.surface,
                    pinyin_plain=code,
                    pinyin_toned=lemma.pinyin_toned,
                    weight=lemma.weight,
                    status=lemma.status,
                    script=lemma.script,
                    categories=list(lemma.categories),
                    flags=list(lemma.flags),
                    entity_type=lemma.entity_type,
                    domain_freq=dict(lemma.domain_freq),
                    sources=list(lemma.sources),
                )
            cleaned.append(lemma)
        buckets[name] = cleaned

    counts = {name: len(items) for name, items in buckets.items()}
    counts["codes_sanitized"] = sanitized
    counts["codes_dropped"] = dropped
    _write_table(out_dir / "umate_chars.dict.yaml", "umate_chars", version, buckets.get("chars", []))
    _write_table(out_dir / "umate_base.dict.yaml", "umate_base", version, buckets.get("base", []))
    for pack in PACK_LAYERS:
        _write_table(out_dir / f"umate_{pack}.dict.yaml", f"umate_{pack}", version, buckets.get(pack, []))
    _write_table(out_dir / "umate_emoji.dict.yaml", "umate_emoji", version, buckets.get("emoji", []))
    _write_core(out_dir / "umate_hans.dict.yaml", version)
    _write_schema(out_dir / "umate_hans.schema.yaml")
    _write_emoji_opencc(out_dir, store)
    _write_notice(out_dir / "NOTICE", store)
    aosp_csv = _resolve_aosp_wordlist()
    if aosp_csv is not None:
        counts.update(emit_aosp_en(aosp_csv, out_dir))
    return counts


def _resolve_aosp_wordlist() -> Path | None:
    """Prefer pinned download extract, then downloads CSV, then fixture."""
    from umate_lexicon.paths import data_dir
    from umate_lexicon.sources import default_downloads_dir

    downloads = default_downloads_dir()
    for name in (
        "aosp_en_US_wordlist.csv",
        "en_US_wordlist.combined.csv",
    ):
        path = downloads / name
        if path.is_file():
            return path
    fixture = data_dir() / "fixtures" / "aosp_en_wordlist.csv"
    if fixture.is_file():
        return fixture
    return None


def _write_core(path: Path, version: str) -> None:
    lines = [
        "# Rime dictionary",
        "# encoding: utf-8",
        "# Generated by umate-lexicon. Do not hand-edit.",
        "---",
        "name: umate_hans",
        f'version: "{version}"',
        "sort: by_weight",
        "use_preset_vocabulary: false",
        "import_tables:",
        "  - umate_chars",
        "  - umate_base",
        "...",
        "",
    ]
    for text, code in LATIN_SYLLABLES:
        lines.append(f"{text}\t{code}")
    for text, code in DIGIT_SYLLABLES:
        lines.append(f"{text}\t{code}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_table(path: Path, name: str, version: str, lemmas: list[Lemma]) -> None:
    lines = [
        "# Rime dictionary",
        "# encoding: utf-8",
        "# Generated by umate-lexicon. Do not hand-edit.",
        "---",
        f"name: {name}",
        f'version: "{version}"',
        "sort: by_weight",
        "use_preset_vocabulary: false",
        "columns:",
        "  - text",
        "  - code",
        "  - weight",
        "...",
        "",
    ]
    ordered = sorted(lemmas, key=lambda item: (-emit_weight(item), item.surface, item.pinyin_plain))
    for lemma in ordered:
        lines.append(f"{lemma.surface}\t{lemma.pinyin_plain}\t{emit_weight(lemma)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_schema(path: Path) -> None:
    packs = "\n".join(f"    - umate_{name}" for name in PACK_LAYERS)
    path.write_text(
        f"""# Rime schema
# encoding: utf-8
# Generated by umate-lexicon. Wire this from VoiMate; do not copy rime-ice.

schema:
  schema_id: umate_hans
  name: uMate Hans
  version: "0.1.0"

engine:
  translators:
    - script_translator
    - table_translator@aosp_en

translator:
  dictionary: umate_hans
  packs:
{packs}
  enable_user_dict: false
""",
        encoding="utf-8",
    )


def _write_emoji_opencc(out_dir: Path, store: LemmaStore) -> None:
    sidecar = emoji_opencc_sidecar(store)
    if not sidecar.is_file():
        return
    dest_dir = out_dir / "opencc"
    dest_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(sidecar, dest_dir / "emoji_word.txt")
    (dest_dir / "NOTICE").write_text(
        "emoji_word.txt is generated from official rime/rime-emoji "
        "(LGPL-3.0). Do not enable simplifier@emoji_suggestion in the "
        "uMate keyboard schema unless that pack is explicitly selected.\n",
        encoding="utf-8",
    )


def _write_notice(path: Path, store: LemmaStore) -> None:
    licenses: dict[str, int] = defaultdict(int)
    for lemma in store.all_lemmas():
        for ref in lemma.sources:
            licenses[f"{ref.source_id} ({ref.license})"] += 1
    body = ["umate-lexicon emit NOTICE", ""]
    for key, count in sorted(licenses.items()):
        body.append(f"{key}: {count} lemmas")
    if (path.parent / "opencc" / "emoji_word.txt").is_file():
        body.append("emoji (lgpl-rime-emoji): opencc/emoji_word.txt")
    if (path.parent / "aosp_en.dict.yaml").is_file():
        body.append("aosp_en (apache-2.0-aosp-latinime): aosp_en.dict.yaml")
        body.append("en_us_unigrams (apache-2.0-aosp-latinime): en_us_unigrams.tsv")
    path.write_text("\n".join(body) + "\n", encoding="utf-8")
